# Generated by Django 5.1 on 2024-08-25 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuralProducers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_or_cnpj', models.CharField()),
                ('producer_name', models.CharField()),
                ('farm_name', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('total_farm_area', models.IntegerField()),
                ('arable_farm_area', models.IntegerField()),
                ('vegetation_farm_area', models.IntegerField()),
                ('cultivated_crops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SOJ', 'Soja'), ('MIL', 'Milho'), ('ALG', 'Algodão'), ('CAF', 'Café'), ('CDA', 'Cana de Açucar')], max_length=10), size=8)),
            ],
        ),
    ]
