# Generated by Django 5.1 on 2024-08-25 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rural_producers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralproducers',
            name='cultivated_crops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SOJA', 'soja'), ('MILHO', 'milho'), ('ALGODÃO', 'algodão'), ('CAFÉ', 'café'), ('CANA DE AÇUCAR', 'cana de açucar')], max_length=20), size=8),
        ),
    ]
